[package]
name = "cad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
imageproc = "0.23.0"
ndarray = "0.15.4"